coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 2%
        
ignore:
  - "cmd/wasm-ffi/main.go"
  - "**/zz_generated*.go"
