name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/release-chart.yml'

permissions:
  contents: read

jobs:
  release:
    # Depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # See: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@f0accbfd55e3332a28f721b8202b1016cecf90d5

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@a0d2dc62c5e491af8ef6ba64a2e02bcf3fb33aa1
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
